name = "FastUnitaryEigenvalues"
uuid = "46119199-b212-4f5e-b2e9-c416668d0e5e"
authors = ["Nicholas West"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
